LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Number is too big!"), "Číslo je príliš veľké!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Amount is too large"), "Suma je príliš veľká");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Please give me a valid crate"), "Zadajte platnú debnu");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Amount cannot be less than 1"), "Suma nesmie byť menšia ako 1");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<Crate> crate does not exist"), "Debna s názvom <Crate> neexistuje");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Current crates: Mythic, Legendary, Rare, Uncommon, Common"), "Dostupné názvy dební: Mythic, Legendary, Rare, Uncommon, Common");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<Crate> is not for sale"), "Debna <Crate> nie je na predaj");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You do not have enough money to buy <Amount> <Crate> crates\n\nYou need <NeededAmount>"), "Nemáte dostatok peňazí na nákup <Amount> <Crate> dební\n\nPotrebujete <NeededAmount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You do not have enough money to buy <Amount> <Crate> crate\n\nYou need <NeededAmount>"), "Nemáte dostatok peňazí na nákup <Amount> <Crate> debne\n\nPotrebujete <NeededAmount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You cannot have more than 999,999,999 crates"), "Nemôžete mať viac ako 999,999,999 dební");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You just bought <Amount> <Crate> crates"), "Práve ste si kúpili <Amount> <Crate> dební");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You just bought <Amount> <Crate> crate"), "Práve ste si kúpili <Amount> <Crate> debnu");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Please give me a valid Amount/Item"), "Prosím, zadajte platnú čiastku/položku");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You can't donate to yourself"), "Nemôžete darovať sám sebe");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Failed to parse string"), "Nepodarilo sa analyzovať reťazec");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You do not have enough money to donate <Amount> You only have <Bal>"), "Nemáte dostatok peňazí na to aby ste darovali <Suma> Máte iba <Bal>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You have successfully given <User> <Amount>"), "Úspešne ste darovali <Amount> používateľovi <User>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Give me a valid food name"), "Zadajte platný názov jedla");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You are already at the max health <MaxHealth>"), "Už ste dosiahli maximále zdravie <MaxHealth>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You just ate an <Food> and you are now at <Health>"), "Zjedli ste <Food> a vaša úroveň zdravia je <MaxHealth>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You just ate a <Food> and you are now at <Health>"), "Zjedli ste <Food> a vaša úroveň zdravia je <MaxHealth>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You have <Owned> <Food> left"), "Zostalo vám <Owned> <Food>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You just went fishing and came back with a <Food>"), "Šli na rybolov a vrátili ste sa s <Food>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You just went fishing and came back with an <Food>"), "Šli na rybolov a vrátili ste sa s <Food>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You just caught a <Food> in the wilderness"), "Ulovili ste <Food> vo voľnej prírode");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You just caught an <Food> in the wilderness"), "Ulovili ste <Food> vo voľnej prírode");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You do not have anything in your inventory"), "Váš inventár je prázdny");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "They do not have anything in their inventory"), "Vo svojom inventári nemajú nič");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You can only open 10 crates at a time"), "Naraz môžete otvoriť iba 10 debien");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You do not own any <Crate> crates"), "Nevlastníte žiadne <Crate> debne");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You do not have enough crates to open <Amount>, you only have <Owned>"), "Nemáte dostatok dební na to aby ste otvorili <Amount>, máte iba <Owned>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Please give me a valid weapon"), "Zadajte platnú zbraň");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You cannot shoot yourself"), "Nemôžete postreliť sám seba");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<Weapon> does not exist"), "<Weapon> neexistuje");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You do not own any <Weapon>'s"), "Nevlastníte žiadnu zbraň s názvom <Weapon>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "This weapon is a knife, Not a gun"), "Táto zbraň je nôž, nie zbraň");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "To use this weapon appropriately use <Shoot>"), "Na správne použitie tejto zbrane použite <Shoot>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Health Before"), "Zdravie predtým");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Health After"), "Zdravie potom");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Money Lost"), "Stratené peniaze");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You cannot have more than the max bal in your wallet"), "V peňaženke nemôžete mať viac");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "The weapon has reached max uses and has been destroyed"), "Zbraň dosiahla maximálne použitie a bola zničená");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You have been killed"), "Boli ste zabití");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "User that killed you"), "Používateľ, ktorý ťa zabil");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<User> Just took 50% of your money <MoneyTaken>"), "<User> vzal 50% vašich peňazí v peňaženke <MoneyTaken>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<User> had a bounty of <Bounty> and it has been collected by <User>"), "<User> mal odmenu za zabitie vo výške <Bounty> a bola prevzianá používateľom <User>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<User> Just shot <User> with a <Weapon>"), "<User> potrelil <User> s <Weapon>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<User> Just shot <User> with a <Weapon> and died"), "<User> zastrelil <User> s <Weapon>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<User> Just shot <User> with an <Weapon>"), "<User> postrelil <User> s <Weapon>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<User> Just shot <User> with an <Weapon> and died"), "<User> zastrelil <User> s <Weapon>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You used this weapon more than it's intended use! This weapon has been deleted from your inventory"), "Túto zbraň ste použili viac, ako je povolené! Táto zbraň bola odstránená z vášho inventára");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You cannot stab yourself"), "Nemôžete sa bodnúť");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<User> Just stabbed <User> with a <Weapon>"), "<User> bodnul <User> s <Weapon>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<User> Just stabbed <User> with a <Weapon> and died"), "<User> dobodal <User> s <Weapon>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<User> Just stabbed <User> with an <Weapon>"), "<User> bodnul <User> s <Weapon>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<User> Just stabbed <User> with an <Weapon> and died"), "<User> dobodal <User> s <Weapon>");
