LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You did not reply in time"), "Neodpovedali ste včas");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<Language> is not a valid language"), "<Language> nie je platný jazyk");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "The servers language is already set to <Language>"), "Jazyk serveru je už nastavený na <Jazyk>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Language has been changed to <Language>"), "Jazyk bol nastavený na <Jazyk>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Please pick the desired language"), "Vyberte požadovaný jazyk");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You have 30 seconds to reply"), "Máte 30 sekúnd na odpoveďy");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You have not voted"), "Nehlasovali ste");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "If you have voted in the last 12 hours please wait a few minutes and try again. Click this link to vote <Link>"), "Ak ste hlasovali za posledných 12 hodín, počkajte niekoľko minút a skúste to znova. Kliknutím na tento odkaz hlasujete <Link>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You have claimed your voting gift"), "Požiadali ste o svoj hlasovací dar");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You claimed your gift for voting and received an <Item>"), "Požiadali ste o svoj dar za hlasovanie a dostali ste <Item>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You claimed your gift for voting and received a <Item>"), "Požiadali ste o svoj dar za hlasovanie a dostali ste <Item>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You claimed your gift for voting and received <Money>, The money you win has been increased due to your <Votes> votes"), "Požiadali ste o darček za hlasovanie a dostali ste <Money>. Peniaze, ktoré vyhráte, sa zvýšili v dôsledku vašich hlasov <Votes>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You claimed your gift for voting and received <Money>"), "Požiadali ste o svoj dar na hlasovanie a dostali ste <Money>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You claimed your gift for voting and received an <Crate> Crate, Your odds have been increased due to your <Votes> votes"), "Požiadali ste o svoj darček za hlasovanie a dostali ste debnu <Crate>, Vaše šance sa zvýšili v dôsledku vašich hlasov <Votes>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You claimed your gift for voting and received a <Crate> Crate, Your odds have been increased due to your <Votes> votes"), "Požiadali ste o svoj darček za hlasovanie a dostali ste debnu <Crate>, Vaše šance sa zvýšili v dôsledku vašich hlasov <Votes>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You claimed your gift for voting and received an <Crate> Crate"), "Požiadali ste o svoj dar za hlasovanie a dostali ste debnu <Crate>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You claimed your gift for voting and received a <Crate> Crate"), "Požiadali ste o svoj dar za hlasovanie a dostali ste debnu <Crate>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You do not have any extra gifts to claim"), "Nemáte na výber žiadne ďalšie dary");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", ":x: Be in the support server\n:x: Nitro boost the support server\n:x: Be a patreon supporter"), ":x: Buďte na podpornom serveri\n:x: Nitro boostnite podporný server\n:x: Staňte sa podporovateľom na patreónu");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You claimed your gift for being a <Role> and recieved"), "Vyžiadali ste si svoj darček za to, že ste <Role> a dostali ste");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Claims"), "Vyžiadanie");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "I have sent the command list to your direct messages"), "Zoznam príkazov som vám odoslala do vašich súkromných správ");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Failed to send direct message. Check privacy settings and try again"), "Nepodarilo sa odoslať súkromnú správu. Skontrolujte nastavenie súkromia a skúste to znova");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Command does not exist!"), "Príkaz neexistuje!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Aliases"), "Prezývky");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Summary"), "Zhrnutie");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Suggestion cannot be empty"), "Návrh nemôže byť prázdny");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Report cannot be empty"), "Nahlásenie nemôže byť prázdne");
