LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Please give me a valid amount"), "Prosím, zadajte platnú čiastku");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Amount must be a number"), "Čiastka musí byť číslo");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Amount must be more than 0"), "Čiastka musí byť viac ako 0");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You do not have enough to place a <Amount> bounty, You only have <Bal>"), "Nemáte dostatok peňazí na to aby ste umiestnili odmenu za zabite v sume <Amount>, máte iba <Bal>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Failed to parse bounty"), "Nepodarilo sa umiestniť odmenu");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You added <Amount> to <User>'s Bounty"), "Pridali ste <Amount> na odmenu za zabitie použivateľa <User>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<Server> Top Bounties"), "<Server> Top odmeny za zabitie");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "There are no bounties in  <Server>"), "V serveri <Server> nie sú žiadne odmeny za zabitie.");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You claimed your gift for voting and received an <Crate> Crate"), "Prevziali ste si svôj darček za hlasovanie a obdržali ste <Crate> bedňu");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You claimed your gift for voting and received a <Crate> Crate"), "Prevziali ste si svôj darček za hlasovanie a obdržali ste <Crate> bedňu");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You have claimed your voting gift"), "Prevziali ste svôj darček za hlasovanie");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You claimed your gift for voting and received an <Prize>"), "Prevziali ste si svôj darček za hlasovanie a obdržali ste <Prize>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You claimed your gift for voting and received a <Prize>"), "Prevziali ste si svôj darček za hlasovanie a obdržali ste <Prize>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You bought a winning lottery ticket and won <Amount>"), "Kúpili ste výherný lotériový lístok a vyhrali ste <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You found a wallet on the ground that contained <Amount>"), "Na zemi ste našli peňaženku, ktorá obsahovala <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You worked at the grocery store and earned <Amount>"), "Pracovali ste v obchode s potravinami a zarobili ste <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You streamed your \"amazing\" content on Twitch and made <Amount>"), "Streamovali ste váš \"úžasný\" obsah na Twitch a zarobili ste <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You went to work as a plumber and earned <Amount>"), "Išli ste pracovať ako inštalatér a zarobili ste  <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "On your way to work you got in a car accident and had to pay <Amount> for the damages"), "Na ceste do práce ste mali dopravnú nehodu a museli ste zaplatiť <Amount> na opravu škôd");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You went to your local grocery store and stole <Amount> from the cash register"), "Išli ste do miestneho obchodu s potravinami a ukradli ste <Amount> z pokladnice");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You found a homeless man on the street. You took all of his possessions and sold it for <Amount>>"), "Na ulici ste našli bezdomovca. Vzali ste všetky jeho veci a predali ste ich za <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You went to church and stole <Amount> from the donation basket"), "Išli ste do kostola a ukradli ste <Amount> z darovnej krabice");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You found a homeless man on the street. When you attempted to rob him he pulled out his badge and fined you <Amount>"), "Na ulici ste našli bezdomovca. Keď ste sa ho pokúsili okradnúť, vytiahol svôj policajný odznak a uložil vám pokutu <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You attempted to rob an old lady, but she robbed you instead for <Amount>"), "Pokúsili ste sa okradnúť starú dámu, ale namiesto toho ona okradla vás o <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You went to your local grocery store attempted to rob it, You were caught by the security guard and fined <Amount>"), "Išli ste do miestneho obchodu s potravinami, pokúsili ste sa ho vykradnúť ale boli ste chytení políciou a uložil vám pokutu <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "The minium desposit is <Amount>"), "Minimálny vklad je <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You do not have enough to deposit <Amount>, You only have <Bal>"), "Nemáte dostatok peňazí na to aby ste mohli vložiť <Amount>, máte iba <Bal>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "**Money Desposited**\n\nYou just deposited <Bal> in your bank\n\nYou now have <Bal> in your wallet and <Bank> in your bank"), "**Peniaze vložené**\n\nPráve ste vložili <Bal> do banky\n\nTeraz máte v peňaženke <Bal> a <Bank> v banke");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<Server>'s Leaderboards"), "<Server> - Rebríček");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "There are no leaderboards in <Server>"), "Nie sú tu žiadne rebríčky v serveri <Server>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "**You Won**\n\nYou rolled a <Number> and won <Bal>"), "**Výhra**\n\nPadlo vám číslo <Number> a vyhrali ste <Bal>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "**You Lost**\n\nYou rolled a <Number> and lost <Bal>"), "**Prehra**\n\nPadlo vám číslo <Number> a stratili ste <Bal>");
