LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You can only bet once"), "Môžete staviť iba raz");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "I have sent you bet list"), "Poslala som ti zoznam stávok");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Failed to send bet list, do you have your dms off?"), "Nepodarilo sa zaslať zoznam stávok, máte vypnutné súkromné správy?");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Pick where you want to place your chip. Type cancel to cancel. (You have 10 seconds to pick where you want to place it)"), "Vyberte si, kam chcete čip umiestniť. Ak chcete akciu zrušiť napíšte cancel. (Máte 10 sekúnd na výber)");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You did not pick where you want to place your chip on time."), "Nevybrali ste si, kam chcete čip umiestniť včas.");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Bet is incorrect. Please cancel your bet and do <RCommand>bets to check what bets you can and cannot do"), "Stávka je nesprávna. Zrušte svoju stávku a napíšte príkaz <RCommand>bets aby ste skontrolovali, aké stávky môžete a nemôžete robiť");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You have canceled your bet"), "Zrušili ste stávku");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Joining Game"), "Pripájanie do hry");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Starting game in <Seconds> seconds"), "Hra začína za <Seconds> sekúnd");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Spinning..."), "Točím...");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Rolled Black <Number>"), "Padla čierna <Number>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Rolled Red <Number>"), "Padla červená <Number>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Roulette Wins"), "Výsledky rulety");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "The minium withdrawal is <Amount>"), "Minimálny výber je <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You do not have enough to withdrawal <Bal>, You only have <Bank>"), "Na výber <Bal> nemáte dosť peňazí, máte iba <Bank>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "**Money Withdrawn**\n\nYou just withdrawn <Bal> from your bank\n\nYou now have <Bal> in your wallet and <Bank> in your bank"), "**Peniaze vybrané**\n\nPráve ste vybrali <Bal> z banky\n\nTeraz máte v peňaženke <Bal> a <Bank> v banke");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You can use their Username, Display Name, Or tag"), "Môžete použiť ich používateľské meno, zobrazené meno alebo tag");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<User> chewed on <User>!"), "<User> rozžul/a <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<User> started turning red?"), "<User> sa začal/a červenať?");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<User> started crying ;("), "<User> začal/a plakať ;(");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<User> started cuddling with <User>! (≧ヘ≦)"), "<User> sa začal/a maznať s <User>! (≧ヘ≦)");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<User> started dancing!"), "<User> začal/a tancovať!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<User> hugged <User>!"), "<User> objal/a <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<User> kissed <User>!"), "<User> pobozkal/a <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<User> licked <User>!"), "<User> olízal/a <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<User> started patting <User>"), "<User> začal/a hladiť na hlave <User>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<User> poked <User>!"), "<User> strčil/a <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<User> punched <User>! :("), "<User> udrel/a <User>! :(");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<User> slapped <User>!"), "<User> dal/a facku <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<User> is getting tired."), "<User> začína byť unavený/á.");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<User> has a smug look on their face >:)"), "<User> má samolibý výraz na tvári >:)");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<User> is staring at <User>!"), "<User> hľadí na <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<User> started tickling <User>!"), "<User> začal/a štekliť <User>!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Image provided by <Provider>"), "Obrázok poskytol <Provider>");
