LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Rem Info"), "Rem Info");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Discord Server"), "Discord Server");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Lead Dev"), "Hlavný vývojár");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Version"), "Verzia");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Servers"), "Servery");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Memory Usage"), "Využitie pamäte");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Website"), "Webstránka");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Made With"), "Vytvorené pomocou");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Discord.Net"), "Discord.Net");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<Day> days, <Hour> hours, <Minute> minutes, <Second> seconds"), "<Day> dní, <Hour> hodnín, <Minute> minút, <Second> sekúnd");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Shard <Shard>"), "Shard <Shard>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Open Database Connections: <Connections>"), "Otvorené databázové pripojenia: <Connections>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "**API Latency** <APILatency>ms\n**Bot Latency** <BotLatency>ms"), "**Latencia API** <APILatency>ms\n**Latencia Bota** <BotLatency>ms");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Ping Result"), "Výsledky Pingu");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You have successfully sent your report to the admins"), "Správu ste úspešne odoslali správcoms");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Thank you for your suggestion!"), "Ďakujeme za váš návrh!");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Cash"), "Hotovosť");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Bank"), "Banka");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Net Worth"), "Net Worth");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "BLACKJACK"), "BLACKJACK");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Your Cards"), "Vaše karty");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Dealers Cards"), "Karty dílera");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "BUST"), "Prehra");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "WIN"), "Výhra");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "PUSH"), "Remíza");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "LOSS"), "Prehra");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Value: <Value>"), "Hodnota: <Value>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Level"), "Level");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "XP"), "XP");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Health"), "Zdravie");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Bounty"), "Odmena za zabitie");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Winners"), "Výhercovia");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Losers"), "Porazení");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Romaji Title"), "Názov v Romanji");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Status"), "Status");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Episodes"), "Epizódy");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Unkown"), "Neznáme");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Air Date"), "Dátum vysielania");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Average Score"), "Priemerné skóre");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Genres"), "Žánre");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "null"), "null");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Trailer"), "Trailer");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "This anime/manga is for adults. If you want to view it you need to be in an nsfw channel"), "Toto anime/manga je určené pre dospelých. Ak ju chcete zobraziť, musíte byť v kanáli s označením NSFW");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Cannot find anime with title <Anime>"), "Nemožno nájsť anime s názvom <Anime>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<Users>'s Avatar!"), "Avatar užívateľa <Users>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Invalid Args"), "Neplatné argumenty");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Please give valid letters to send"), "Zadajte platné slová na odoslanie");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Content is to long, Message needs to be under 2000 characters."), "Obsah je dlhý, správa musí mať menej ako 2000 znakov.");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "It is certain"), "Je to isté");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "It is decidedly so"), "Je to rozhodne tak");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Without a doubt"), "Bezpochýb");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Yes definitely"), "Rozhodne áno");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You may rely on it"), "Môžete sa na to spoľahnúť");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "As I see it yes"), "Ako to vidím, áno");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Most likely"), "Pravdepodobne");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Outlook good"), "Vyzerá to tak");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Yes"), "Áno");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Signs point to yes"), "Značky poukazujú na áno");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Reply hazy try again"), "Odpoveď zakaždým skúste");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Ask again later"), "Opýtajte sa znova neskôr");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Better not tell you now"), "Radšej ti to teraz nepoviem");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Cannot predict now"), "Momentálne nie je možné predvídať");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Concentrate and ask again"), "Koncentrujte a opýtajte sa znova");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Don't count on it"), "Nepočítajte s tým");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "My reply is no"), "Moja odpoveď je nie");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "My sources say no"), "Moje zdroje hovoria nie");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Outlook not so good"), "Nevyzerá to tak");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Very doubtful"), "Veľmi pochybné");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Question <Question>"), "Otázka <Question>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Answer <Answer>"), "Odpoveď <Answer>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Coinflip"), "Hodenie mincou");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "The coin landed on Heads"), "Minca pristála na hlavách");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "The coin landed on Tails"), "Minca pristála na chvostoch");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Cannot find anime with genre <Genre> and year <Year>"), "Anime s žánrom <Genre> a rokom <Year> sa nepodarilo nájsť");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Cannot find anime with year <Year>"), "Nemožno nájsť anime s rokom <Rok>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Cannot find anime with genre <Genre>"), "Nemožno nájsť anime s žánrom <Genre>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Genre/Year is empty"), "Žáner/rok je prázdny");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Anime is empty"), "Anime je prázdne");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "I do not have permission to delete messages"), "Nemám povolenie na mazanie správ");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Common Crate"), "Common debna");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Uncommon Crate"), "Uncommon debna");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Rare Crate"), "Rare debna");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Legendary Crate"), "Legendary debna");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Mythic Crate"), "Mythic debna");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "**Common Winnings**"), "**Bežné výhry**");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "**Uncommon Winnings**"), "**Nezvyčajné výhry**");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "**Rare Winnings**"), "**Vzácne výhry**");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "**Legendary Winnings**"), "**Legendárne výhry**");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "**Mythic Winnings**"), "**Mýtické výhry**");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Price"), "Cena");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Common Odds"), "Pravdepodobnosť bežných");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Uncommon Odds"), "Pravdepodobnosť nezvyčajných");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Rare odds"), "Pravdepodobnosť vzácnych");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Legendary Odds"), "Pravdepodobnosť legendárnych");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Mythic Odds"), "Pravdepodobnosť mýtických");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Type"), "Typ");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Rarity"), "Rarita");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Uses"), "Použitia");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Damage"), "Poškodenie");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Can Open"), "Môže sa otvoriť");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Kills"), "Zabitia");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Deaths"), "Smrti");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "K/D Ratio"), "Pomer Z/S");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Damage Done"), "Udelené poškodenie");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Won From Gambling"), "Výhry z gamblingu");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Lost From Gambling"), "Prehry z gamblingu");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Failed to get stats"), "Nepodarilo sa získať štatistiky");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Statistic must be an Item, Crate, or a User"), "Štatistika musí byť položka, debna alebo užívateľ");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You can only use nsfw commands in nsfw channels"), "NSFW príkazy môžete použiť iba v kanáloch s označením NSFW");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Lewd Neko"), "Lewd Neko");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Rem Lewd"), "Rem Lewd");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Thicc Thighs"), "Thicc Thighs");
