LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Bets"), "Stávky");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You need to ask Rem a question for a prediction"), "Musíte položiť otázku na predpoveď");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "You need the `Manage Messages` permission on this channel to use this command"), "Na použitie tohto príkazu potrebujete povolenie `Spravovať správy` na tomto kanáli");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Please give me a message to repeat"), "Prosím, zadajte správu na zopakovanie");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Weapons"), "Zbrane");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Crates"), "Debny");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Food"), "Jedlo");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<Weapon> Owned: <Amount> Uses: <Uses>"), "<Weapon> Vlastníš: <Amount> Použitia: <Uses>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "<Type> Owned: <Amount>"), "<Type> Vlastníš: <Amount>");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "This weapon is a gun, not a knife"), "Toto je strelná zbraň, nie nôž");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Common"), "Common");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Uncommon"), "Uncommon");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Rare"), "Rare");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Legendary"), "Legendary");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Mythic"), "Mythic");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Gun"), "Strelná zbraň");
LanguageDictionary.TryAdd(new KeyValuePair<string, string>("Slovak", "Knife"), "Nôž");
